### ISSUE TITLE
No module named pox.core

### ISSUE THREAD

**Issue by pavankumarjavvaji** [uqfoundation/pox#38]
Showing there is no module named pox. Core ans pox. Lib can you help me how to solve it

**Comment by mmckerns** [comment]
have you `pip install pox` from the terminal?

**Comment by pavankumarjavvaji** [comment]
Yaa i did even though it is showing issue

**Comment by mmckerns** [comment]
So, you are saying that `pip` does not seem to find `pox`?

**Comment by pavankumarjavvaji** [comment]
It is not able to find pox.Core  every time i am trying it is show same error how to fix it

**Comment by pavankumarjavvaji** [comment]
It is able to run other things

**Comment by mmckerns** [comment]
There is no pox.core module

**Comment by pavankumarjavvaji** [comment]
Then what should i use in place of it?

**Comment by mmckerns** [comment]
You have the wrong `pox`: https://github.com/att/pox/blob/master/pox/core.py

**Comment by pavankumarjavvaji** [comment]
Pox contains core. Py right?

**Comment by mmckerns** [comment]
I'll assume I can close this.  Reopen if needed.
